In [1]:
!pip install numpy


   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
    --------------------------------------- 0.3/12.9 MB ? eta -:--:--
    --------------------------------------- 0.3/12.9 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.9 MB 567.2 kB/s eta 0:00:22
   - -------------------------------------- 0.5/12.9 MB 567.2 kB/s eta 0:00:22
   -- ------------------------------------- 0.8/12.9 MB 564.9 kB/s eta 0:00:22
   -- ------------------------------------- 0.8/12.9 MB 564.9 kB/s eta 0:00:22
   --- ------------------------------------ 1.0/12.9 MB 578.7 kB/s eta 0:00:21
   --- ------------------------------------ 1.0/12.9 MB 578.7 kB/s eta 0:00:21
   ---- ----------------------------------- 1.3/12.9 MB 583.0 kB/s eta 0:00:20
   ---- ----------------------------------- 1.3/12.9 MB 583.0 kB/s eta 0:00:20
   ---- ----------

In [2]:
import numpy as np

In [8]:
x=np.array([1,2,3,4,5,6])
print(x)
print(type(x))
print(x.ndim)
print("length",len(x))
x=np.append(x,5)
print(x)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1
length 6
[1 2 3 4 5 6 5]


In [12]:
print(x*2)
print(x/2)
print(x-2)
print(x+2)
print(x*2/2)
print(x%2)

[ 2  4  6  8 10 12 10]
[0.5 1.  1.5 2.  2.5 3.  2.5]
[-1  0  1  2  3  4  3]
[3 4 5 6 7 8 7]
[1. 2. 3. 4. 5. 6. 5.]
[1 0 1 0 1 0 1]


In [13]:
import numpy as xyz

In [17]:
x=np.array([1,2,3,4,5,6])
print(x)

[1 2 3 4 5 6]


In [21]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,1])
print(a,b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)

[1 2 3 4 5] [6 7 8 9 1]
[ 7  9 11 13  6]
[-5 -5 -5 -5  4]
[ 6 14 24 36  5]
[0.16666667 0.28571429 0.375      0.44444444 5.        ]
[1 2 3 4 0]


In [26]:
a=np.array([[1,2,3],[1,2,3]])
b=np.array([[4,5,6],[1,2,3]])
c=a+b
c=a-b
print(c)

[[-3 -3 -3]
 [ 0  0  0]]


In [29]:
number=np.zero(6)
matrix=np.zero((3,4))
print(number)
print(matrix)


AttributeError: module 'numpy' has no attribute 'zero'

In [31]:
number=np.ones(6)
matrix=np.ones((3,4))
print(number)
print(matrix)

[1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
random=np.random.rand(10)
print(random)

[0.76713664 0.75416782 0.32847575 0.93395599 0.20301108 0.32806216
 0.68604209 0.99841698 0.20066516 0.64089221]


In [33]:
ages=np.random.rand(3,4)
print(ages)

[[0.39428695 0.87283254 0.65030471 0.6307803 ]
 [0.61383324 0.75039021 0.71698102 0.91835201]
 [0.50659037 0.31986869 0.86989651 0.259463  ]]


In [35]:
point=np.linspace(1,20,num=6)
print(point)

[ 1.   4.8  8.6 12.4 16.2 20. ]


In [36]:
done=np.linspace(1,100,num=20)
print(done)

[  1.           6.21052632  11.42105263  16.63157895  21.84210526
  27.05263158  32.26315789  37.47368421  42.68421053  47.89473684
  53.10526316  58.31578947  63.52631579  68.73684211  73.94736842
  79.15789474  84.36842105  89.57894737  94.78947368 100.        ]


In [39]:
arr1=np.array([1,2,3,4,5])
arr2=arr1
arr1[2]=23
print(arr1)
print(arr2)


[ 1  2 23  4  5]
[ 1  2 23  4  5]


In [41]:
arr1=np.array([1,2,3,4,5])
arr2[2]=arr1.copy()
arr2[2]=23
print(arr1)
print(arr2)

ValueError: setting an array element with a sequence.

In [42]:
a=5
b=4
print(np.power(a,b))


625


In [43]:
a=np.array([1,2,3,4,5])
b=np.array([3,4,5,6,7])
print(np.power(a,b))

[    1    16   243  4096 78125]


In [48]:
a=np.array([[1,2,3], [2,3,4]])
b=np.array([[3,2,1],[4,6,2]])
print(np.power(a,b))

[[  1   4   3]
 [ 16 729  16]]
